# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: orangeMoon个人笔记
email: ""
description: >-
  算法笔记、Unity、C# 与 C++ 个人笔记。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rangemoon.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: rangemoon
lang: zh-CN
minima:
  date_format: "%Y-%m-%d %H:%M"

header_pages:
  - algorithm.md
  - unity.md
  - csharp.md
  - cpp.md

collections:
  algorithm:
    output: true
    permalink: /algorithm/:name/
  unity:
    output: true
    permalink: /unity/:name/
  csharp:
    output: true
    permalink: /csharp/:name/
  cpp:
    output: true
    permalink: /cpp/:name/

defaults:
  - scope:
      path: ""
      type: algorithm
    values:
      layout: post
      module: 算法笔记
  - scope:
      path: ""
      type: unity
    values:
      layout: post
      module: Unity
  - scope:
      path: ""
      type: csharp
    values:
      layout: post
      module: C#
  - scope:
      path: ""
      type: cpp
    values:
      layout: post
      module: C++

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
